## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop (columns = ["EIN", "NAME"])
#app_df.head()

In [ ]:
# Determine the number of unique values in each column.
unique_values = application_df.nunique()

In [ ]:
# Look at APPLICATION_TYPE value counts for binning
app = application_df['APPLICATION_TYPE'].value_counts()
app

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app[app > 1000].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
Other    32033
T8         737
T7         725
T10        528
T9         156
T13         66
T12         27
T2          16
T25          3
T14          3
T29          2
T15          2
T17          1
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts for binning
clasify = application_df['CLASSIFICATION'].value_counts()
clasify

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
cc = clasify[clasify > 1]
cc

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(clasify[clasify > 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
Other    32038
C7000      777
C1700      287
C4000      194
C5000      116
         ...
C4120        1
C8210        1
C1245        1
C2561        1
C2150        1
Name: count, Length: 67, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
num_df = pd.get_dummies(application_df)

In [ ]:
num_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,True,False,False,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,True,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,True,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34295,1,5000,0,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34296,1,5000,0,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34297,1,5000,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
34298,1,36500179,0,True,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,True,False

In [ ]:
# Split our preprocessed data into our features and target arrays
X = num_df.drop(["IS_SUCCESSFUL"], axis='columns').values
y = num_df["IS_SUCCESSFUL"].values

# Split the preprocessed data into a training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
nn_model = tf.keras.models.Sequential()
number_input_features = len(X_train[0])

# First hidden layer
nn_model.add(tf.keras.layers.Dense(units=80, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn_model.add(tf.keras.layers.Dense(units=30, activation="relu"))

# Output layer
nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 80)                8720

 dense_4 (Dense)             (None, 30)                2430

 dense_5 (Dense)             (None, 1)                 31

=================================================================
Total params: 11181 (43.68 KB)
Trainable params: 11181 (43.68 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [ ]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.6024 - accuracy: 0.7052
Epoch 2/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5842 - accuracy: 0.7131
Epoch 3/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5808 - accuracy: 0.7144
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5792 - accuracy: 0.7166
Epoch 5/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5787 - accuracy: 0.7160
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5774 - accuracy: 0.7151
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5767 - accuracy: 0.7166
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5765 - accuracy: 0.7165
Epoch 9/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5763 - accuracy: 0.7173
Epoch 10/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5754 - accuracy: 0.7172
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5757 - accuracy: 0.7168
Epoch 12/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5750 - accuracy: 0.7172
Epoch 13/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5747 - accuracy: 0.7177
Epoch 14/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5746 - accuracy: 0.7182
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5739 - accuracy: 0.7174
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5740 - accuracy: 0.7183
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5744 - accuracy: 0.7194
Epoch 18/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5739 - accuracy: 0.7182
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5736 - accuracy: 0.7194
Epoch 20/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5733 - accuracy: 0.7181
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5732 - accuracy: 0.7191
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5733 - accuracy: 0.7191
Epoch 23/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5728 - accuracy: 0.7188
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5730 - accuracy: 0.7196
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5731 - accuracy: 0.7194
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5727 - accuracy: 0.7202
Epoch 27/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5725 - accuracy: 0.7194
Epoch 28/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5721 - accuracy: 0.7202
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5720 - accuracy: 0.7206
Epoch 30/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5722 - accuracy: 0.7204
Epoch 31/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5719 - accuracy: 0.7198
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5717 - accuracy: 0.7192
Epoch 33/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5721 - accuracy: 0.7191
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5718 - accuracy: 0.7205
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5716 - accuracy: 0.7193
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5715 - accuracy: 0.7204
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5715 - accuracy: 0.7200
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5709 - accuracy: 0.7206
Epoch 39/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5709 - accuracy: 0.7201
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5713 - accuracy: 0.7199
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5713 - accuracy: 0.7192
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5708 - accuracy: 0.7200
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5713 - accuracy: 0.7201
Epoch 44/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5711 - accuracy: 0.7201
Epoch 45/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5705 - accuracy: 0.7205
Epoch 46/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5710 - accuracy: 0.7203
Epoch 47/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5704 - accuracy: 0.7201
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5706 - accuracy: 0.7199
Epoch 49/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5704 - accuracy: 0.7203
Epoch 50/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5705 - accuracy: 0.7207
Epoch 51/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5704 - accuracy: 0.7210
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5702 - accuracy: 0.7211
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5701 - accuracy: 0.7207
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5703 - accuracy: 0.7196
Epoch 55/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5698 - accuracy: 0.7209
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5701 - accuracy: 0.7213
Epoch 57/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5697 - accuracy: 0.7206
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5701 - accuracy: 0.7215
Epoch 59/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5699 - accuracy: 0.7205
Epoch 60/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5696 - accuracy: 0.7213
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5699 - accuracy: 0.7204
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5701 - accuracy: 0.7211
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5699 - accuracy: 0.7213
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5694 - accuracy: 0.7210
Epoch 65/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5695 - accuracy: 0.7207
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5693 - accuracy: 0.7208
Epoch 67/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5695 - accuracy: 0.7216
Epoch 68/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5691 - accuracy: 0.7212
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5694 - accuracy: 0.7206
Epoch 70/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5691 - accuracy: 0.7203
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5691 - accuracy: 0.7208
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5692 - accuracy: 0.7216
Epoch 73/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5693 - accuracy: 0.7212
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5688 - accuracy: 0.7210
Epoch 75/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5692 - accuracy: 0.7214
Epoch 76/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5691 - accuracy: 0.7209
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5694 - accuracy: 0.7214
Epoch 78/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5690 - accuracy: 0.7215
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5693 - accuracy: 0.7203
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5689 - accuracy: 0.7213
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5690 - accuracy: 0.7208
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5687 - accuracy: 0.7212
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5688 - accuracy: 0.7214
Epoch 84/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5684 - accuracy: 0.7220
Epoch 85/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5688 - accuracy: 0.7214
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5689 - accuracy: 0.7212
Epoch 87/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5689 - accuracy: 0.7214
Epoch 88/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5685 - accuracy: 0.7216
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5690 - accuracy: 0.7214
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5685 - accuracy: 0.7218
Epoch 91/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5687 - accuracy: 0.7210
Epoch 92/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5686 - accuracy: 0.7217
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5683 - accuracy: 0.7211
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5685 - accuracy: 0.7216
Epoch 95/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5687 - accuracy: 0.7215
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5683 - accuracy: 0.7218
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5683 - accuracy: 0.7208
Epoch 98/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5691 - accuracy: 0.7212
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5680 - accuracy: 0.7222
Epoch 100/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5682 - accuracy: 0.7210

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5960 - accuracy: 0.7075 - 872ms/epoch - 3ms/step
Loss: 0.5959877967834473, Accuracy: 0.7075218558311462

In [ ]:
# Export our model to HDF5 file
hdf5store = pd.HDFStore('AlaphabetSoupCharity.h5')